repos:
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.17 # Get the latest from: https://github.com/gruntwork-io/pre-commit/releases
    hooks:
      - id: terraform-fmt
      - id: terraform-validate
  - repo: https://github.com/bridgecrewio/checkov.git
    rev: 2.2.139 # change to tag or sha
    hooks:
      - id: checkov
        args: [-o, junitxml, result.xml]