trigger: none
  
jobs:
- template: 'templates/build.yml'
  parameters:
    publish_artifact_contents: |
                              .terraform.lock.hcl
                              *.tf
                              modules/**
  