name: _template_setup_statestore

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      resource_group:
        required: true
        type: string
      storage_account:
        required: true
        type: string
      resource_location:
        required: true
        type: string

jobs:
  setup-state-store:
    runs-on: ubuntu-latest
    
    environment: ${{ inputs.environment }}

    env: 
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

    steps:
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          creds: '{"clientId":"${{ secrets.ARM_CLIENT_ID }}","clientSecret":"${{ secrets.ARM_CLIENT_SECRET }}","subscriptionId":"${{ secrets.ARM_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.ARM_TENANT_ID }}"}'
      
      - name: 'Run az commands'
        shell: pwsh
        run: |
          echo "*** Check if Resource Group ${{ inputs.resource_group }} exists"
          $checkRg = az group exists --name ${{ inputs.resource_group }} | ConvertFrom-Json
          if (!$checkRg) {
            Write-Warning "*** WARN! Resource Group ${{ inputs.resource_group }} does not exist. Creating..."

            az group create --name ${{ inputs.resource_group }} --location "${{ inputs.resource_location }}"
            if ($LastExitCode -ne 0) {
              throw "*** Error - could not create resource group"
            }
          }
          else
          {
            echo "*** Ok"
          }
          echo "*** Check if Storage Account ${{ inputs.storage_account }} exists"
          $check = az storage account show --name ${{ inputs.storage_account }} `
                                          --resource-group ${{ inputs.resource_group }} | ConvertFrom-Json
          if (!$check) {
            Write-Warning "*** WARN! Storage Account ${{ inputs.storage_account }} does not exist. Creating..."
            az storage account create --name ${{ inputs.storage_account }} `
                                      --resource-group ${{ inputs.resource_group }} `
                                      --https-only true `
                                      --sku Standard_GZRS `
                                      --min-tls-version TLS1_2
            if ($LastExitCode -ne 0) {
              throw "*** Error - could not create storage account"
            }
          }
          else
          {
            echo "*** Ok"
          }

          $terraformContainerName = "tfstate"
          echo "*** Check if Container $terraformContainerName exists"

          $key = az storage account keys list -n ${{ inputs.storage_account }} -g ${{ inputs.resource_group }} --query "[0].{value:value}" --output tsv
          $check = az storage container exists --account-name ${{ inputs.storage_account }} --account-key $key`
                                              --name $terraformContainerName | ConvertFrom-Json
          if (!$check.exists) {
            Write-Warning "*** WARN! Container $terraformContainerName does not exist. Creating..."
            az storage container create --name $terraformContainerName `
                                        --account-name ${{ inputs.storage_account }} `
                                        --public-access off `
                                        --account-key $key

            if ($LastExitCode -ne 0) {
              throw "*** Error - could not create storage container"
            }
          }
          else
          {
            echo "*** Ok"
          }
