name: Setup TF state store INT

on:
  workflow_dispatch:


jobs:
  deploy:
    name: Deploy INT
    uses: ./.github/workflows/_template_deploy_foundation.yml
    with: 
      environment: 'test'
      resource_group: 'rg-moc-tfstate-we-dev-001'
      storage_account: 'stmoctfstatedev001'
      tfvar_file: 'env-int.tfvars'
      container_name: 'tfstate'
      state_file: 'foundation123.tfstate'
    secrets: inherit
    

