name: Setup TF state store INT

on:
  workflow_dispatch:

env:
  RESOURCE_LOCATION: 'West Europe'

jobs:
  deploy:
    name: Deploy INT
    uses: ./.github/workflows/_template_setup_statestore.yml
    with: 
      environment: 'test'
      resource_group: 'rg-moc-tfstate-we-dev-001'
      storage_account: 'stmoctfstatedev001'
      resource_location: 'West Europe'
    secrets: inherit
    

