name: Setup TF state store INT

on:
  workflow_dispatch:

env:
  RESOURCE_GROUP: 'rg-moc-tfstate-we-dev-001'
  STORAGE_ACCOUNT: 'stmoctfstatedev001'
  RESOURCE_LOCATION: 'West Europe'

jobs:
  deploy:
    name: Deploy INT
    uses: ./.github/workflows/_template_setup_statestore.yml
    with: 
      environment: 'test'
      resource_group: {{ $env.RESOURCE_GROUP }}
      storage_account: $STORAGE_ACCOUNT
      resource_location: $RESOURCE_LOCATION
    secrets: inherit
    

