name: Setup TF state store INT

on:
  workflow_dispatch:

env:
  RESOURCE_LOCATION: 'West Europe'

jobs:
  deploy:
    name: Deploy INT
    uses: ./.github/workflows/_template_setup_statestore.yml
    with: 
      environment: 'test'
    secrets: inherit
    

