name: Setup TF state store

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Target environment
        default: 'test'
        required: true

env:
  RESOURCE_LOCATION: 'West Europe'

jobs:
  deploy-test:
    uses: ./.github/workflows/workflow_setup_statestore.yml
    with: 
      environment: 'test'
    secrets: inherit

  deploy-prod:
    uses: ./.github/workflows/workflow_setup_statestore.yml
    needs: [deploy-test]
    with: 
      environment: 'prod'
    secrets: inherit
    

