name: Setup TF state store

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Target environment
        default: 'test'
        required: true

env:
  RESOURCE_LOCATION: 'West Europe'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    environment: ${{ github.event.inputs.environment }}

    env: 
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      RESOURCE_GROUP_NAME: 'RG-TF-STATE-001-DEV'
      STORAGE_ACCOUNT_NAME: 'stmoclocaldev01'

    steps:
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          creds: '{"clientId":"${{ secrets.ARM_CLIENT_ID }}","clientSecret":"${{ secrets.ARM_CLIENT_SECRET }}","subscriptionId":"${{ secrets.ARM_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.ARM_TENANT_ID }}"}'
      
      - name: 'Run az commands'
        shell: pwsh
        run: |
          echo "*** Check if Resource Group ${env:RESOURCE_GROUP_NAME} exists"
          $checkRg = az group exists --name ${env:RESOURCE_GROUP_NAME} | ConvertFrom-Json
          if (!$checkRg) {
            Write-Warning "*** WARN! Resource Group ${env:RESOURCE_GROUP_NAME} does not exist. Creating..."

            az group create --name ${env:RESOURCE_GROUP_NAME} --location "${env:RESOURCE_LOCATION}"
            if ($LastExitCode -ne 0) {
              throw "*** Error - could not create resource group"
            }
          }
          else
          {
            echo "*** Ok"
          }
          echo "*** Check if Storage Account ${env:STORAGE_ACCOUNT_NAME} exists"
          $check = az storage account show --name ${env:STORAGE_ACCOUNT_NAME} `
                                          --resource-group ${env:RESOURCE_GROUP_NAME} | ConvertFrom-Json
          if (!$check) {
            Write-Warning "*** WARN! Storage Account ${env:STORAGE_ACCOUNT_NAME} does not exist. Creating..."
            az storage account create --name ${env:STORAGE_ACCOUNT_NAME} `
                                      --resource-group ${env:RESOURCE_GROUP_NAME} `
                                      --https-only true `
                                      --sku Standard_GZRS `
                                      --min-tls-version TLS1_2
            if ($LastExitCode -ne 0) {
              throw "*** Error - could not create storage account"
            }
          }
          else
          {
            echo "*** Ok"
          }
